In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.11.0+cpu


In [ ]:
##Introduction to tensor

##creating tensors

##PyTorch tensors are created using `torch.tensor()`


In [ ]:
##scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
##This gives scalar dimentions
scalar.ndim

0

In [ ]:
#get tensor back as Python int
scalar.item()

7

In [ ]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
 ##vector dimention
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX=torch.tensor([[7,8],
                   [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape


torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                     [4,5,6],
                     [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#create a random tensor of size (3, 4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8180, 0.5931, 0.5373, 0.4801],
        [0.1699, 0.9368, 0.4629, 0.3723],
        [0.3541, 0.2744, 0.5339, 0.0673]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a randome tensor with similar shape to an image tensor
randome_image_size_tensor=torch.rand(size=(3,224,224)) # colour, height, width channel (R, G, B)
randome_image_size_tensor.shape, randome_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

###Zeros and ones

In [ ]:
#Crete a tenosr of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#ceate a tensor of all ones
ones=torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

#Create a range of Tensor and Tensor-like

In [ ]:
#use torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_1000=torch.arange(start=1, end=1000, step=77)
one_to_1000

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [ ]:
#Creating tensor like
ten_zeros = torch.zeros_like (input=one_to_1000)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##tensor datatype

In [ ]:
# Float 32 tensor
float_32_tensor= torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, #what datatype is the tensor (e.g. float32 or float16)
                              device=None, #what device is your tensor on
                              requires_grad=False)#whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

Getting informations from tensors (tensor attributes)

 1. Tensors not right data type-to do get datatype from a tensor , can use tensor.dtype
 2. Tensorn not right shape- to get shape from a tensosr, can use tensor.shape
 3. Tensor not on the right device- to get device from a tensor, can use tensor.device

In [ ]:
#create a randome tensor
some_tensor = torch.rand (3, 4)
some_tensor

tensor([[0.7921, 0.1319, 0.1497, 0.7131],
        [0.6607, 0.5813, 0.9317, 0.1952],
        [0.1292, 0.4736, 0.9848, 0.1058]])

In [ ]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Tensor device: {some_tensor.device}")

tensor([[0.7921, 0.1319, 0.1497, 0.7131],
        [0.6607, 0.5813, 0.9317, 0.1952],
        [0.1292, 0.4736, 0.9848, 0.1058]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Tensor device: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
#cerate a tensor and add 10 to it
tensor= torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#Multiply tensor by 10
tensor *10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract 10
tensor-10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplicaion in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

THere are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimentions** must match:

*`(3,2) @ (3,2)` wont work

*`(2,3) @ (3,2)` will work

*`(3,2) @ (2,3)` will work

2. The resulting matrix has the sape of the **outer dimentions**:

*(2, 3) @ (3, 2) -> (2, 2)

*(3, 2) @ (2, 3) -> (3, 3)

In [ ]:
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
#by hand
1*1+2*2+3*3

14

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value +=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 187 µs, sys: 2.75 ms, total: 2.94 ms
Wall time: 7.54 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 851 µs, sys: 0 ns, total: 851 µs
Wall time: 629 µs


tensor(14)

##One of the most common errors in deep learning is: shape errors

In [ ]:
#shapes for matrix multiplicatiosn
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,10],
                      [8, 11],
                      [9,12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

To fix our tensor sahpe issue, we can manupulate the shape of one of our tesnors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B, tensor_B.shape

In [ ]:
tensor_B.T, tensor_B.T.shape

In [ ]:
#The matrix multiplication operaion works when tensor_B is transposed
print(f"Original shape: tensor_A = {tensor_A.shape}, tensor_B= {tensor_B.shape}")
print(f"New shape: tensor_A= {tensor_A.shape}, tensor_B.T= {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <-inner dimnesions must match ")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\n output shoae: {output.shape}")

#Find the min,max,mean,sum.etc (tesnor aggregation)

In [ ]:
#create a tensor
x = torch.arange(1,100,10)
x

In [ ]:
#find the min
torch.min(x), x.min()

In [ ]:
#find the max
torch.min(x), x.max()

In [ ]:
#find the mean--note: the torch.mean() function requires a tensor of float32 datdatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
#find the sum
torch.sum(x), x.sum()

## Finding the positional min and max

In [ ]:
#FInf the position in tensor the has the minimum value with argmun()- return index position position of target tensor where the minimum value occurs
x.argmin()

In [ ]:
x


In [ ]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

In [ ]:
x[9]

##Reshaping,stacking, squeezing and unsqueezing tngenosr

* reshaping- reshapes an input tensor to a defeined shape

* View - return a view of an input rensor of cirtain shape but keep the same memory as the original tesor

* Stacking - combine multiple tensor on top of each other (vstack) or side by side (hsatck)

* Squeeze - rempve all `1` dimention to a target tensor

* Unsqueeze - add a `1` dimention to a target tensor

* permute - Return a view of the input with dimentions permuted (swapped) in a certain way

In [ ]:
#Lets create a tensor

x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add a extra dimention
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes the x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack tensor on top of each other
x_stacked = torch.stack([x,x,x,x] , dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])