<a href="https://colab.research.google.com/github/BlackCoder8/Pytorch/blob/main/00_pyotrch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.11.0+cu128


In [2]:
##Introduction to tensor

##creating tensors

##PyTorch tensors are created using `torch.tensor()`


In [3]:
##scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
##This gives scalar dimentions
scalar.ndim

0

In [5]:
#get tensor back as Python int
scalar.item()

7

In [6]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
 ##vector dimention
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
MATRIX=torch.tensor([[7,8],
                   [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape


torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                     [4,5,6],
                     [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
#create a random tensor of size (3, 4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.9204, 0.9816, 0.9186, 0.7370],
        [0.5647, 0.9438, 0.0125, 0.0116],
        [0.5908, 0.8214, 0.3114, 0.2957]])

In [18]:
random_tensor.ndim

2

In [19]:
#create a randome tensor with similar shape to an image tensor
randome_image_size_tensor=torch.rand(size=(3,224,224)) # colour, height, width channel (R, G, B)
randome_image_size_tensor.shape, randome_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

###Zeros and ones

In [20]:
#Crete a tenosr of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
#ceate a tensor of all ones
ones=torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

#Create a range of Tensor and Tensor-like

In [25]:
#use torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
one_to_1000=torch.arange(start=1, end=1000, step=77)
one_to_1000

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [27]:
#Creating tensor like
ten_zeros = torch.zeros_like (input=one_to_1000)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##tensor datatype

In [28]:
# Float 32 tensor
float_32_tensor= torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, #what datatype is the tensor (e.g. float32 or float16)
                              device=None, #what device is your tensor on
                              requires_grad=False)#whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

Getting informations from tensors (tensor attributes)

 1. Tensors not right data type-to do get datatype from a tensor , can use tensor.dtype
 2. Tensorn not right shape- to get shape from a tensosr, can use tensor.shape
 3. Tensor not on the right device- to get device from a tensor, can use tensor.device

In [32]:
#create a randome tensor
some_tensor = torch.rand (3, 4)
some_tensor

tensor([[0.1510, 0.3752, 0.5079, 0.6038],
        [0.8033, 0.6978, 0.3901, 0.7849],
        [0.2259, 0.5920, 0.0472, 0.1704]])

In [33]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Tensor device: {some_tensor.device}")

tensor([[0.1510, 0.3752, 0.5079, 0.6038],
        [0.8033, 0.6978, 0.3901, 0.7849],
        [0.2259, 0.5920, 0.0472, 0.1704]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Tensor device: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [34]:
#cerate a tensor and add 10 to it
tensor= torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [35]:
#Multiply tensor by 10
tensor *10

tensor([10, 20, 30])

In [36]:
tensor

tensor([1, 2, 3])

In [37]:
# Subtract 10
tensor-10

tensor([-9, -8, -7])

In [38]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [39]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplicaion in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

THere are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimentions** must match:

*`(3,2) @ (3,2)` wont work

*`(2,3) @ (3,2)` will work

*`(3,2) @ (2,3)` will work

2. The resulting matrix has the sape of the **outer dimentions**:

*(2, 3) @ (3, 2) -> (2, 2)

*(3, 2) @ (2, 3) -> (3, 3)

In [40]:
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [41]:
#matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
#by hand
1*1+2*2+3*3

14

In [43]:
%%time
value=0
for i in range(len(tensor)):
  value +=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 0 ns, sys: 1.82 ms, total: 1.82 ms
Wall time: 4.11 ms


In [44]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 686 µs, sys: 0 ns, total: 686 µs
Wall time: 651 µs


tensor(14)

##One of the most common errors in deep learning is: shape errors

In [45]:
#shapes for matrix multiplicatiosn
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,10],
                      [8, 11],
                      [9,12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

To fix our tensor sahpe issue, we can manupulate the shape of one of our tesnors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor

In [46]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [48]:
#with the help of transpose
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [49]:
#The matrix multiplication operaion works when tensor_B is transposed
print(f"Original shape: tensor_A = {tensor_A.shape}, tensor_B= {tensor_B.shape}")
print(f"New shape: tensor_A= {tensor_A.shape}, tensor_B.T= {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <-inner dimnesions must match ")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\n output shoae: {output.shape}")

Original shape: tensor_A = torch.Size([3, 2]), tensor_B= torch.Size([3, 2])
New shape: tensor_A= torch.Size([3, 2]), tensor_B.T= torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <-inner dimnesions must match 
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 output shoae: torch.Size([3, 3])


#Find the min,max,mean,sum.etc (tesnor aggregation)

In [50]:
#create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [51]:
#find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [52]:
#find the max
torch.min(x), x.max()

(tensor(1), tensor(91))

In [53]:
#find the mean--note: the torch.mean() function requires a tensor of float32 datdatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [54]:
#find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [55]:
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [56]:
#FInf the position in tensor the has the minimum value with argmun()- return index position position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [57]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [58]:
x[9]

tensor(91)

##Reshaping,stacking, squeezing and unsqueezing tensor

* reshaping- reshapes an input tensor to a defeined shape

* View - return a view of an input tensor of cirtain shape but keep the same memory as the original tesor

* Stacking - combine multiple tensor on top of each other (vstack) or side by side (hsatck)

* Squeeze - rempve all `1` dimention to a target tensor

* Unsqueeze - add a `1` dimention to a target tensor

* permute - Return a view of the input with dimentions permuted (swapped) in a certain way

In [59]:
import torch

In [86]:
#Lets create a tensor

x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [89]:
#Add a extra dimention
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [84]:
#Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [82]:
#changing z changes the x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [83]:
#Stack tensor on top of each other
x_stacked = torch.stack([x,x,x,x] , dim=1)
x_stacked

tensor([[[[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [90]:
#torch.squeeze()- removes all single dimensions from a target tensor
print(f"Previous tesnor{x_reshaped}")
print(f"Previous shape {x_reshaped.shape}")

#remove extra dimentions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tesnortensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [66]:
#torch.unsqueeze() -  adds a single dimention to a  target tensor at a specific dim(dimentions)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimention with unsqueeze

x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tesnor: {x_unsqueezed}")
print(f"\nNew tensor: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tesnor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New tensor: torch.Size([1, 9])


In [67]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [68]:
#torch.permute - rearrange the dimnetions of a target tensor in a specific order
x_original =torch.rand(size=(224, 224, 3)) #[height, width, color_chanels]

# permute the original tensor to rearrange the axis (or dim) orde
x_permuted = x_original.permute(2, 0, 1) #shifts 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")#[color_chanel, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [69]:
x_original[0, 0, 0] = 728218
x_permuted

tensor([[[7.2822e+05, 7.9687e-01, 8.5163e-01,  ..., 3.6522e-01,
          4.2200e-02, 4.7249e-01],
         [6.9816e-01, 4.2745e-02, 1.9387e-01,  ..., 1.0410e-01,
          2.7079e-01, 1.6708e-01],
         [7.8864e-01, 5.0399e-01, 6.2648e-01,  ..., 8.8254e-01,
          9.5733e-01, 6.6704e-01],
         ...,
         [1.8343e-01, 9.1800e-01, 7.9210e-01,  ..., 7.6435e-01,
          6.4042e-01, 3.3507e-01],
         [1.7322e-01, 4.2123e-02, 9.5186e-01,  ..., 8.9347e-01,
          3.3097e-01, 3.9104e-02],
         [9.3690e-01, 4.7286e-01, 9.8338e-01,  ..., 9.0000e-01,
          5.7574e-01, 1.6289e-01]],

        [[3.9928e-01, 4.2011e-01, 5.0632e-01,  ..., 3.9710e-01,
          4.2730e-01, 4.3767e-01],
         [3.6634e-01, 6.4266e-01, 6.2000e-01,  ..., 2.3188e-01,
          8.9737e-01, 6.8864e-01],
         [8.0028e-01, 9.9209e-01, 5.8897e-01,  ..., 5.9577e-01,
          5.4040e-01, 6.6306e-01],
         ...,
         [6.2361e-01, 4.3651e-01, 3.5350e-01,  ..., 9.2621e-01,
          2.833

## Indexing (select data from tesnor)
indexing with Pytorch in similar to indexing with NumPy

In [70]:
#create a tensor
import torch
x = torch.arange(1,10). reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [71]:
#Lets index on out new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [72]:
#lets index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [73]:
#lets index on most innter bracket (last dimention)
x[0][0][0]

tensor(1)